server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param

resilience4j:
  circuitbreaker:
    instances:
      accountService:
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 2
        slowCallDurationThreshold: 2s
        slowCallRateThreshold: 100
        automaticTransitionFromOpenToHalfOpenEnabled: true
        registerHealthIndicator: true

      creditService:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3

  timelimiter:
    instances:
      accountService:
        timeoutDuration: 2s
      creditService:
        timeoutDuration: 2s
